#=======================================
# LOGGING
#=======================================
quarkus.log.level=INFO
quarkus.log.category."org.jboss.sbomer".level=DEBUG
quarkus.log.console.format=%d{HH:mm:ss,SSS} %-5p traceId=%X{traceId} parentId=%X{parentId} spanId=%X{spanId} [%c{3.}] (%t) %s%e mdc:[%X]%n

#=======================================
# OBSERVABILITY
#=======================================
quarkus.otel.enabled=true
quarkus.otel.traces.enabled=true
quarkus.otel.traces.sampler=always_on
quarkus.otel.metrics.enabled=true
quarkus.otel.logs.enabled=true

#=======================================
# APPLICATION
#=======================================

# Manifest Storage Service REST Client
manifest-storage/mp-rest/url=${MANIFEST_STORAGE_INTERNAL_URL}
manifest-storage/mp-rest/connectTimeout=10000
manifest-storage/mp-rest/readTimeout=120000

#=======================================
# KAFKA - GLOBAL PRODUCER CONFIG
#=======================================
# These settings apply to ALL outgoing Kafka channels
kafka.apicurio.registry.auto-register=true
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS}
kafka.apicurio.registry.url=${SCHEMA_REGISTRY_URL}

#=======================================
# ENHANCER METADATA
#=======================================
sbomer.enhancer.tool.name=${SBOMER_ENHANCER_TOOL_NAME:SBOMer}
sbomer.enhancer.tool.version=${SBOMER_ENHANCER_TOOL_VERSION:1.0.0}
sbomer.enhancer.supplier.name=${SBOMER_ENHANCER_SUPPLIER_NAME:Red Hat}
# Note: For Lists, pass them as comma-separated strings
sbomer.enhancer.supplier.urls=${SBOMER_ENHANCER_SUPPLIER_URLS:https://www.redhat.com}

#=======================================
# KAFKA - CHANNEL DEFINITIONS
#=======================================

# OUTGOING

# --- 'sbomer-errors' channel ---
mp.messaging.outgoing.sbomer-errors.topic=sbomer.errors
mp.messaging.outgoing.sbomer-errors.connector=smallrye-kafka
mp.messaging.outgoing.sbomer-errors.value.serializer=io.apicurio.registry.serde.avro.AvroKafkaSerializer
mp.messaging.outgoing.sbomer-errors.apicurio.registry.url=${SCHEMA_REGISTRY_URL}
mp.messaging.outgoing.sbomer-errors.apicurio.registry.auto-register=true

# --- 'enhancement-update' channel ---
mp.messaging.outgoing.enhancement-update.topic=enhancement.update
mp.messaging.outgoing.enhancement-update.connector=smallrye-kafka
mp.messaging.outgoing.enhancement-update.value.serializer=io.apicurio.registry.serde.avro.AvroKafkaSerializer
mp.messaging.outgoing.enhancement-update.apicurio.registry.url=${SCHEMA_REGISTRY_URL}
mp.messaging.outgoing.enhancement-update.apicurio.registry.auto-register=true

# INCOMING

# --- 'enhancement-created' channel ---
mp.messaging.incoming.enhancement-created.topic=enhancement.created
mp.messaging.incoming.enhancement-created.connector=smallrye-kafka
mp.messaging.incoming.enhancement-created.value.deserializer=io.apicurio.registry.serde.avro.AvroKafkaDeserializer
mp.messaging.incoming.enhancement-created.apicurio.registry.url=${SCHEMA_REGISTRY_URL}
mp.messaging.incoming.enhancement-created.apicurio.registry.auto-register=true
mp.messaging.incoming.enhancement-created.apicurio.registry.use-specific-avro-reader=true